#!/bin/bash
set -e

# Generate NOTAMAPIConfig.xcconfig from environment variables
# This script runs after Xcode Cloud clones the repository

CONFIG_DIR="$CI_PRIMARY_REPOSITORY_PATH/SF50 TOLD/NOTAM"
CONFIG_FILE="$CONFIG_DIR/NOTAMAPIConfig.xcconfig"

# Ensure the directory exists
mkdir -p "$CONFIG_DIR"

# Generate the xcconfig file from CI environment variables
cat > "$CONFIG_FILE" << EOF
//
// NOTAMAPIConfig.xcconfig
// SF50-TOLD
//
// Generated by Xcode Cloud CI
//

// NOTAM API Token for https://notams.fly.dev
NOTAM_API_TOKEN = ${NOTAM_API_TOKEN}

// NOTAM API Base URL
NOTAM_API_BASE_URL = ${NOTAM_API_BASE_URL//:/:/\$()}
EOF

echo "Generated NOTAMAPIConfig.xcconfig"

# Install sentry-cli for debug symbol uploads
echo "Installing sentry-cli..."
curl -sL https://sentry.io/get-cli/ | bash
echo "sentry-cli installed: $(sentry-cli --version)"
